# Generated by Django 5.2.6 on 2025-09-27 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Chile', max_length=80)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('category', models.CharField(choices=[('discoteque', 'Discoteque'), ('pub', 'Pub'), ('restaurant', 'Restaurante'), ('rooftop', 'Rooftop'), ('other', 'Otro')], max_length=20)),
                ('cover_image', models.ImageField(blank=True, upload_to='venues/covers/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=120)),
                ('payment_methods', models.JSONField(blank=True, null=True)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('reservation_url', models.URLField(blank=True)),
                ('hours_short', models.CharField(blank=True, max_length=80)),
                ('bar_highlights', models.JSONField(blank=True, null=True)),
                ('bar_recommended_title', models.CharField(blank=True, default='Recomendado del bartender', max_length=120)),
                ('bar_recommended_body', models.TextField(blank=True)),
                ('bar_promos', models.JSONField(blank=True, null=True)),
                ('bar_menu_pdf', models.URLField(blank=True)),
                ('bar_menu_qr_url', models.URLField(blank=True)),
                ('happy_hour_note', models.CharField(blank=True, max_length=140)),
                ('is_published', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='places.city')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to=settings.AUTH_USER_MODEL)),
                ('vibe_tags', models.ManyToManyField(blank=True, related_name='venues', to='places.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('category', models.CharField(blank=True, choices=[('party', 'Carrete/Fiesta'), ('concert', 'Concierto'), ('standup', 'Stand-up'), ('electronic', 'Electrónica'), ('other', 'Otro')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('flyer_image', models.ImageField(blank=True, upload_to='events/flyers/%Y/%m/')),
                ('eyebrow_text', models.CharField(blank=True, max_length=60)),
                ('badge_text', models.CharField(blank=True, max_length=60)),
                ('external_ticket_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('feature_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='places.city')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='places.venue')),
            ],
        ),
    ]
