# Generated by Django 5.2.6 on 2025-09-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Commune',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='city',
            new_name='Commune',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='city',
            new_name='Commune',
        ),
    ]
