# Generated by Django 5.2.6 on 2025-09-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_city_commune_rename_city_event_commune_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='bar_highlights',
            new_name='highlights',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='bar_menu_pdf',
            new_name='menu_qr_url',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='bar_menu_qr_url',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='bar_promos',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='bar_recommended_body',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='bar_recommended_title',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='happy_hour_note',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='price_level',
        ),
        migrations.AddField(
            model_name='venue',
            name='gallery_venue',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='menu_pdf',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='recommended_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='recommended_title',
            field=models.CharField(blank=True, default='Recomendado del bartender', max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='vgt_promos_1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='vgt_promos_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='vgt_promos_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
