# Generated by Django 5.2.6 on 2025-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_bar_highlights_venue_highlights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='payment_methods',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta y Efectivo', 'Tarjeta y Efectivo'), ('Tarjeta y Transferencia', 'Tarjeta y Transferencia'), ('Efectivo y Transferencia', 'Efectivo y Transferencia')], max_length=50, null=True, blank=True),
        ),
    ]
