# Generated by Django 5.2.6 on 2025-09-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_venue_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='highlights',
        ),
        migrations.AddField(
            model_name='venue',
            name='highlights_1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='venue',
            name='highlights_2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='venue',
            name='highlights_3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
