# Generated by Django 5.2.6 on 2025-09-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_venue_highlights_venue_highlights_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='experience_venue',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
