# Generated by Django 5.2.6 on 2025-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_venue_experience_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, upload_to='venues/logos/%Y/%m/'),
        ),
    ]
