# Generated by Django 5.2.6 on 2025-10-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_venue_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='image',
            field=models.ImageField(blank=True, upload_to='communes/%Y/%m/'),
        ),
    ]
