# Generated by Django 5.1 on 2025-11-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_commune_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='payment_methods',
            field=models.CharField(blank=True, choices=[('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta y Efectivo', 'Tarjeta y Efectivo'), ('Tarjeta y Transferencia', 'Tarjeta y Transferencia'), ('Efectivo y Transferencia', 'Efectivo y Transferencia'), ('Todo medio de pago', 'Todo medio de pago')], max_length=50, null=True),
        ),
    ]
