# Generated by Django 5.1 on 2025-11-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_event_clicks_count_event_last_clicked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='highlights_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='highlights_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='highlights_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vgt_promos_1',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vgt_promos_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='vgt_promos_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
