# Generated by Django 5.2.6 on 2025-09-27 17:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Dueño de local'), ('guest', 'Asistente')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=120, verbose_name='Nombre del local')),
                ('admin_name', models.CharField(max_length=120, verbose_name='Nombre administrador')),
                ('rut_comercio', models.CharField(max_length=14, verbose_name='RUT comercio')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Correo corporativo')),
                ('company_domain', models.CharField(max_length=120, verbose_name='Dominio comercial')),
                ('owner_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('is_adult', models.BooleanField(default=False, verbose_name='Mayor de edad')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='account.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
