# Generated by Django 5.2.6 on 2025-09-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_ownerprofile_guestprofile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofile',
            name='is_adult',
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
