# Generated by Django 5.2.6 on 2025-09-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_guestprofile_is_adult_guestprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='company_domain',
            field=models.CharField(max_length=120, unique=True, verbose_name='Dominio comercial'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo corporativo'),
        ),
    ]
