# Generated by Django 5.2.5 on 2025-10-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ownerprofile_company_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='foto_personal',
            field=models.ImageField(blank=True, null=True, upload_to='guest_photos/', verbose_name='Foto personal'),
        ),
    ]
