# Generated by Django 5.1 on 2025-11-05 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='override_reason',
            field=models.CharField(blank=True, help_text='Motivo (cortesía, convenio, soporte, etc.)', max_length=200),
        ),
        migrations.AddField(
            model_name='subscription',
            name='override_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], help_text='Si se define, este estado manda sobre el de Mercado Pago.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='override_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la que aplica el override manual.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], default='PAUSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
