# Generated by Django 5.1 on 2025-11-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_subscription_created_at_subscription_override_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], help_text='Si se define, reemplaza temporalmente el estado real de Mercado Pago.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
