# Generated by Django 5.1 on 2025-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='mp_preapproval_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_reason',
            field=models.CharField(blank=True, help_text='Motivo (cortesía, convenio, soporte, etc.)', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('CANCELLED', 'Cancelada')], help_text='Si se define, este estado manda sobre el de Mercado Pago.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='override_until',
            field=models.DateTimeField(blank=True, help_text='Fecha hasta la que aplica el override manual.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
