# Generated by Django 5.1 on 2025-11-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='is_subscribed_admin',
            field=models.BooleanField(default=False, help_text='Marcar manualmente para activar la suscripción del dueño.', verbose_name='Suscrito (Admin)'),
        ),
    ]
