# Generated by Django 5.1 on 2025-11-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_ownerprofile_is_subscribed_admin'),
        ('places', '0010_event_clicks_count_event_last_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='places.commune', verbose_name='Comuna de residencia'),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
    ]
